# Configuração do backend para se conectar com o Netlify e o GitHub
backend:
  name: git-gateway
  branch: main # ou master, dependendo da sua branch principal

# Onde as imagens (logos) serão salvas no seu projeto
media_folder: "img"
# Como o site irá acessar essas imagens
public_folder: "/img"

# Define as coleções de conteúdo gerenciáveis (neste caso, os Parceiros)
collections:
  - name: "sponsors"
    label: "Parceiros"
    folder: "_sponsors"
    create: true
    slug: "{{slug}}"
    fields: # Lista de campos para cada Parceiro
      - { label: "Ordem de Exibição", name: "order", widget: "number", min: 1, default: 100 }
      - { label: "Nome do Parceiro", name: "name", widget: "string" }
      - { label: "Logo", name: "logo", widget: "image" }
      - { label: "Telefone", name: "phone", widget: "string" }
      - { label: "Endereço", name: "address", widget: "string" }