# Configuração do backend para se conectar com o Netlify e o GitHub
backend:
  name: git-gateway
  branch: main

# Configuração de mídia
media_folder: "img"
public_folder: "/img"

# Definição das coleções
collections:
  - name: "sponsors"
    label: "Parceiros"
    folder: "_sponsors"
    create: true
    slug: "{{slug}}"
    sort: "name:asc"
    fields:
      - label: "Nome do Parceiro"
        name: "name"
        widget: "string"
      - label: "Categoria"
        name: "category"
        widget: "select"
        options: ["Alimentação", "Assistêcia Técnica", "Moda&Beleza", "Pet Shop", "Serviços", "Serviços Gráficos", "Transporte", "Utilidades"]
      - label: "Logo"
        name: "logo"
        widget: "image"
      - label: "Telefone"
        name: "phone"
        widget: "string"
      - label: "Endereço"
        name: "address"
        widget: "string"
